---
title: "Contextualização"
author: "MCIMD 2020-1"
date: "3/30/2020"
indent: yes
output:
  pdf_document: default
  html_document: default
---

# Simulação da evolução do COVID-19 em cidades pequenas e possibilidades de manejo 

## Contextualização



A rápida propagação do vírus COVID-19 e suas implicações no âmbitos de saúde pública e econômico pegaram o mundo de surpresa em 2020. Por se tratar de uma nova situação, há muitas dúvidas e perguntas não respondidas, fazendo com que os gestores públicos sintam-se despreparados para tomar decisões.


Mesmo quando as decisões são tomadas, não há consenso quanto à sua efetividade, devido à falta de conhecimento científico e empírico sobre a doença e suas formas de propagação. O campo da simulação computacional pode ser de grande valia na tomada de decisões de combate à pandemias. 


Nesse ímpeto, a turma de Métodos Computacionais Intensivos para Mineração de Dados do Programa de Pós-Graduação Aplicada - PPCA da UnB recebeu a incumbência de, orientados pelo professor [Guilherme Rodrigues](https://github.com/Guilherme-Souza-Rodrigues), desenvolver em conjunto um modelo de simulação de resposta ao COVID_19.
 

## Objetivos


Este trabalho aspira modelar como as cidades pequenas devem se proteger do vírus.  As três políticas analisadas são:

* isolamento [vide exemplo em Minas Gerais](https://oglobo.globo.com/sociedade/coronavirus-cidade-no-interior-de-mg-se-isola-por-conta-propria-controla-entrada-de-visitantes-24320734)
* minimização das interações sociais
* combinação dessas estratégias.



Através dos resultados de simulação obtidos será possível determinar qual das três opções é a mais efetiva.



## Premissas e limitações do modelo


A cidade escolhida para a simulação é a cidade de Santana do Jacaré, tendo como limites geográficos para o estudo o retângulo definido pelos pontos : 

* (-20.896826, -45.128259)
* (-20.896826, -45.131666)
* (-20.903345, -45.128259)
* (-20.903345, -45.128259)


Essa cidade é marcada pela ausência de espaços verticais e pouca influência do transporte coletivo na movimentação diária dos moradores. Por suas pequenas dimensões, e poucos acessos seria fácil impor isolamento.



```{r simulacao}
        # incluir plot do momento inicial
        # incluir plot do momento final de uma das simulações

```



A simulação constará de XXXX passos, perfazendo um total de YYYY dias. 


## Trabalhos adicionais

### Estudo do impacto das mortes
### Estudo do impacto da movimentação de agentes alheios à cidade

## Produtos entregues :



* Dashboard
* Artigo
* Video
* Animações
* Mapas


## Resultado esperado

## Possíveis melhorias e futuras implementações




